# destination: ../www/
port: 80
permalink: /articles/:categories/:title/
# permalink: pretty
# site settings
title: "Mickaël DEVOLDÈRE" 
slogan: ""
subtitle: Formateur &amp; Développeur
description: Ressources et guides pour aspirants développeurs<br /> disponibles sous license Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
#author: MDevoldere

banner: /assets/img/banner.jpg

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
github_url: https://github.com/mdevoldere
gitlab_url: https://gitlab.com/mdevoldere
linkedin_url: https://www.linkedin.com/in/devoldere

# build settings
markdown: kramdown

sass:
  style: compressed
